In [1]:
import pycaret
print(pycaret.__version__)

3.3.2

In [2]:
import numpy as np
SEED = 7
np.random.seed(SEED)

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
import pandas as pd
from pycaret.classification import *

# Load your preprocessed dataset
df = pd.read_csv(r"C:\Users\manis\Downloads\preprocessed_multiple_class.csv")

# Target column
target = 'attack type'

# Show quick overview
print(df.shape)
df.head()

(35000, 36)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC27,PC28,PC29,PC30,PC31,PC32,PC33,PC34,PC35,attack type
0,-1.844530,0.003013,-0.077057,-0.214017,-0.604202,0.785226,0.088003,0.488782,-1.089147,-0.266907,...,-0.399339,0.442995,0.380217,0.086113,0.398695,-0.038791,-0.000418,-0.035242,-0.071810,Bot
1,-2.114291,-0.053045,0.379540,-0.046920,1.242315,0.119263,0.000331,-0.628133,-0.882525,2.033132,...,0.033110,-1.786123,0.818943,-0.538143,-0.264298,0.011855,-0.000585,0.031274,0.022991,Web Attack
2,-1.842625,0.002847,-0.075887,-0.213708,-0.604181,0.785390,0.087978,0.487524,-1.089749,-0.267633,...,-0.400734,0.442891,0.379991,0.086025,0.398904,-0.038814,-0.000419,-0.034028,-0.072332,Bot
3,-1.478224,-0.010469,0.011352,-0.011329,-0.400250,1.592338,0.161982,0.952709,-2.091688,-0.096761,...,-0.242185,-0.208548,0.288761,0.077288,0.315320,-0.026143,-0.000367,0.311215,-0.128024,Web Attack
4,-1.902913,0.026170,-0.273082,-0.080753,-0.567086,1.085976,0.120778,0.802664,-1.394595,-0.442245,...,-0.094592,0.409424,0.065545,0.266979,0.509591,-0.036566,-0.001091,0.010120,-0.101205,Port Scan

In [5]:
# Setup PyCaret
s = setup(
    data=df,
    target=target,
    session_id=42,
    log_experiment=False,
    use_gpu=False
)

In [6]:
best_model = compare_models(sort='F1', n_select=1)
print(best_model)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [7]:
# Evaluate performance visually
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [8]:
multiclass_models = [
    'lightgbm',
    'xgboost',
    'et',
    'rf',
    'catboost'
]

In [9]:
from pycaret.classification import *
import pandas as pd

def get_fold_scores(model_list, metric="F1", fold=5):

    scores = {}

    for model_name in model_list:

        print(f"Training {model_name}...")

        create_model(model_name, fold=fold)

        results = pull()

        # Remove Mean and Std rows
        fold_scores = results.iloc[:-2][metric].astype(float).tolist()

        scores[model_name] = fold_scores

    return scores

In [10]:
multiclass_scores = get_fold_scores(
    multiclass_models,
    metric="F1",
    fold=5
)

Training lightgbm...

Training xgboost...

Training et...

Training rf...

Training catboost...

In [11]:
from itertools import combinations
from scipy.stats import ttest_rel, wilcoxon
import pandas as pd

def pairwise_tests(scores):

    rows = []

    for m1, m2 in combinations(scores.keys(), 2):

        t_stat, t_p = ttest_rel(scores[m1], scores[m2])

        w_stat, w_p = wilcoxon(scores[m1], scores[m2])

        rows.append({
            "Model 1": m1,
            "Model 2": m2,
            "t-statistic": round(t_stat,4),
            "t p-value": round(t_p,6),
            "Wilcoxon Statistic": round(w_stat,4),
            "Wilcoxon p-value": round(w_p,6)
        })

    return pd.DataFrame(rows)

In [12]:
multiclass_stats = pairwise_tests(multiclass_scores)

multiclass_stats

,Model 1,Model 2,t-statistic,t p-value,Wilcoxon Statistic,Wilcoxon p-value
0,lightgbm,xgboost,-0.2911,0.785437,4.5,0.853923
1,lightgbm,et,1.7295,0.158776,1.0,0.144127
2,lightgbm,rf,2.8139,0.048128,1.0,0.125000
3,lightgbm,catboost,4.7809,0.008770,0.0,0.062500
4,xgboost,et,1.7722,0.151060,3.0,0.312500
5,xgboost,rf,3.5455,0.023896,0.0,0.067889
6,xgboost,catboost,2.8180,0.047925,0.0,0.062500
7,et,rf,0.6065,0.576933,6.0,0.812500
8,et,catboost,0.6864,0.530178,4.0,0.437500
9,rf,catboost,0.3750,0.726697,5.5,0.812500

In [13]:
!pip install autogluon

Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.1.3)
Requirement already satisfied: scipy<1.17,>=1.5.4 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.15.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.4.2)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.2.3)
Requirement already satisfied: tqdm<5,>=4.38 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.1)
Requirement already satisfied: requests in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.3)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.43.58-py3-none-any.whl.metadata (6.6 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (19.0.0)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (5.9.0)
Requirement already satisfied: joblib<1.7,>=1.2 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.4.2)
Requirement already satisfied: pyyaml>=5.0 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (6.0.2)
Collecting hyperopt<0.2.8,>=0.2.7 (from autogluon.core[all]==1.5.0->autogluon)
  Using cached hyperopt-0.2.7-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (11.1.0)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Using cached torch-2.9.1-cp313-cp313-win_amd64.whl.metadata (30 kB)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Using cached transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
Collecting accelerate<2.0,>=0.34.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Collecting fsspec<=2025.3 (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: jsonschema<4.24,>=4.18 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (4.23.0)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp313-cp313-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.0)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Collecting omegaconf<2.4.0,>=2.1.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading omegaconf-2.3.1-py3-none-any.whl.metadata (4.5 kB)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in c:\users\manis\anaconda3\lib\site-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Collecting tensorboard<3,>=2.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.3-py3-none-any.whl.metadata (6.9 kB)
Collecting lightgbm<4.7,>=4.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Using cached lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-win_amd64.whl.metadata (2.0 kB)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting fastai<2.9,>=2.3.1 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading fastai-2.8.7-py3-none-any.whl.metadata (8.6 kB)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting einops<0.9,>=0.7 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Collecting spacy<3.9 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading spacy-3.8.14-cp313-cp313-win_amd64.whl.metadata (28 kB)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.3-py3-none-any.whl.metadata (10.0 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1.tar.gz (2.9 MB)
     ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
     --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
     --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
     --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
     ------- -------------------------------- 0.5/2.9 MB 448.6 kB/s eta 0:00:06
     ---------- ----------------------------- 0.8/2.9 MB 520.8 kB/s eta 0:00:05
     ---------- ----------------------------- 0.8/2.9 MB 520.8 kB/s eta 0:00:05
     -------------- ------------------------- 1.0/2.9 MB 586.9 kB/s eta 0:00:04
     -------------- ------------------------- 1.0/2.9 MB 586.9 kB/s eta 0:00:04
     ------------------ --------------------- 1.3/2.9 MB 585.6 kB/s eta 0:00:03
     --------------------- ------------------ 1.6/2.9 MB 634.2 kB/s eta 0:00:03
     --------------------- ------------------ 1.6/2.9 MB 634.2 kB/s eta 0:00:03
     ------------------------- -------------- 1.8/2.9 MB 685.2 kB/s eta 0:00:02
     -------------------------------- ------- 2.4/2.9 MB 786.5 kB/s eta 0:00:01
     -------------------------------- ------- 2.4/2.9 MB 786.5 kB/s eta 0:00:01
     -------------------------------- ------- 2.4/2.9 MB 786.5 kB/s eta 0:00:01
     -------------------------------- ------- 2.4/2.9 MB 786.5 kB/s eta 0:00:01
     ------------------------------------ --- 2.6/2.9 MB 685.0 kB/s eta 0:00:01
     ---------------------------------------- 2.9/2.9 MB 707.5 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.7-py3-none-any.whl.metadata (18 kB)
Collecting orjson~=3.9 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl.metadata (43 kB)
Collecting chronos-forecasting<2.4,>=2.2.2 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading chronos_forecasting-2.3.1-py3-none-any.whl.metadata (24 kB)
Collecting peft<0.18,>=0.13.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading peft-0.17.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\manis\anaconda3\lib\site-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon) (24.2)
Collecting safetensors>=0.4.3 (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting botocore<1.44.0,>=1.43.58 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading botocore-1.43.58-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\manis\anaconda3\lib\site-packages (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.0.1)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\manis\anaconda3\lib\site-packages (from botocore<1.44.0,>=1.43.58->boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\manis\anaconda3\lib\site-packages (from botocore<1.44.0,>=1.43.58->boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.3.0)
Collecting graphviz (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: plotly in c:\users\manis\anaconda3\lib\site-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (5.24.1)
Requirement already satisfied: six in c:\users\manis\anaconda3\lib\site-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.5.0->autogluon) (1.17.0)
Collecting datasets>=2.0.0 (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading datasets-5.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: dill in c:\users\manis\anaconda3\lib\site-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon) (0.3.8)
Collecting xxhash (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading xxhash-3.8.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting multiprocess (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Collecting fastdownload<2,>=0.0.5 (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading fastdownload-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Collecting fastcore>=1.8.0 (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading fastcore-2.1.12-py3-none-any.whl.metadata (5.6 kB)
Collecting fasttransform>=0.0.2 (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading fasttransform-0.0.2-py3-none-any.whl.metadata (7.6 kB)
Collecting fastprogress>=0.2.4 (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading fastprogress-1.1.6-py3-none-any.whl.metadata (4.9 kB)
Collecting plum-dispatch (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading plum_dispatch-2.9.0-cp313-cp313-win_amd64.whl.metadata (7.1 kB)
Requirement already satisfied: cloudpickle in c:\users\manis\anaconda3\lib\site-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.5.0->autogluon) (3.0.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\manis\anaconda3\lib\site-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (3.11.10)
Requirement already satisfied: pydantic<3,>=1.7 in c:\users\manis\anaconda3\lib\site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (2.10.3)
Collecting toolz~=0.10 (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\manis\anaconda3\lib\site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (4.12.2)
Requirement already satisfied: filelock in c:\users\manis\anaconda3\lib\site-packages (from huggingface_hub<1.0->huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon) (3.17.0)
Collecting future (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon)
  Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting py4j (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.5.0->autogluon)
  Using cached py4j-0.10.9.9-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\manis\anaconda3\lib\site-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.5.0->autogluon) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\manis\anaconda3\lib\site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\manis\anaconda3\lib\site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\manis\anaconda3\lib\site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\manis\anaconda3\lib\site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.5.0->autogluon) (0.22.3)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting pytorch-lightning (from lightning<2.6,>=2.5.1->autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_lightning-2.6.5-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\manis\anaconda3\lib\site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\manis\anaconda3\lib\site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\manis\anaconda3\lib\site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\manis\anaconda3\lib\site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\manis\anaconda3\lib\site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.2.0)
Requirement already satisfied: numba in c:\users\manis\anaconda3\lib\site-packages (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (0.61.0)
Collecting optuna (from mlforecast<0.15.0,>=0.14.0->autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)

  DEPRECATION: Building 'nvidia-ml-py3' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'nvidia-ml-py3'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  DEPRECATION: Building 'antlr4-python3-runtime' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'antlr4-python3-runtime'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  DEPRECATION: Building 'seqeval' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'seqeval'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  error: subprocess-exited-with-error

  Building wheel for statsforecast (pyproject.toml) did not run successfully.
  exit code: 1

  [63 lines of output]
  C:\Users\manis\AppData\Local\Temp\pip-build-env-km7juxyx\overlay\Lib\site-packages\setuptools\dist.py:765: SetuptoolsDeprecationWarning: License classifiers are deprecated.
  !!

          ********************************************************************************
          Please consider removing the following classifiers in favor of a SPDX license expression:

          License :: OSI Approved :: Apache Software License

          See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
          ********************************************************************************

  !!
    self._finalize_license_expression()
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\arima.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\ces.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\core.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\ets.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\feature_engineering.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\garch.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\mfles.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\models.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\mstl.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\tbats.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\theta.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\utils.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\_modidx.py -> build\lib.win-amd64-cpython-313\statsforecast
  copying python\statsforecast\__init__.py -> build\lib.win-amd64-cpython-313\statsforecast
  creating build\lib.win-amd64-cpython-313\statsforecast\adapters
  copying python\statsforecast\adapters\prophet.py -> build\lib.win-amd64-cpython-313\statsforecast\adapters
  copying python\statsforecast\adapters\__init__.py -> build\lib.win-amd64-cpython-313\statsforecast\adapters
  creating build\lib.win-amd64-cpython-313\statsforecast\distributed
  copying python\statsforecast\distributed\fugue.py -> build\lib.win-amd64-cpython-313\statsforecast\distributed
  copying python\statsforecast\distributed\multiprocess.py -> build\lib.win-amd64-cpython-313\statsforecast\distributed
  copying python\statsforecast\distributed\__init__.py -> build\lib.win-amd64-cpython-313\statsforecast\distributed
  running egg_info
  writing python\statsforecast.egg-info\PKG-INFO
  writing dependency_links to python\statsforecast.egg-info\dependency_links.txt
  writing entry points to python\statsforecast.egg-info\entry_points.txt
  writing requirements to python\statsforecast.egg-info\requires.txt
  writing top-level names to python\statsforecast.egg-info\top_level.txt
  reading manifest file 'python\statsforecast.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'CONTRIBUTING.md'
  warning: no previously-included files found matching 'Makefile'
  warning: no previously-included files found matching 'environment.yml'
  warning: no previously-included files found matching '.gitconfig'
  warning: no previously-included files found matching '.gitignore'
  warning: no previously-included files found matching '.gitmodules'
  warning: no previously-included files matching '*' found under directory '.github'
  warning: no previously-included files matching '*' found under directory 'docs'
  warning: no previously-included files matching '*' found under directory 'examples'
  warning: no previously-included files matching '*' found under directory 'experiments'
  warning: no previously-included files matching '*' found under directory 'nbs'
  warning: no previously-included files matching '*' found under directory 'tests'
  adding license file 'LICENSE'
  writing manifest file 'python\statsforecast.egg-info\SOURCES.txt'
  running build_ext
  building 'statsforecast._lib' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for statsforecast
ERROR: Failed to build installable wheels for some pyproject.toml based projects (statsforecast)

In [ ]:
from autogluon.tabular import TabularPredictor
from sklearn.metrics import accuracy_score, f1_score

predictor = TabularPredictor(
    label=target,
    eval_metric="f1"
).fit(
    train_data=train_df,
    presets="best_quality",
    time_limit=3600
)

pred = predictor.predict(test_df) 

print("Accuracy:", accuracy_score(test_df[target], pred))
print("F1:", f1_score(test_df[target], pred))